#!/bin/bash
# check all certificates one or more folders for is validity, similar to the check_http certificate check.
# nice-to-have for openvpn certificate monitoring, folders with certs in general (e.g. easy-rsa)
# there will be a separated check for each folder summarizing all certs while showing certs in WARN / CRIT state as well as the one closest to its expiry date

#Set your limits here:
WARN_DAYS=28
CRIT_DAYS=14

# Configure the folders at the very bottom!
####

function check_certs_in_folder {
leastexpirationdate=0
leastexpirationcert=""
desc=""
folder=$(basename -- $1)
for TARGET in $1/*.crt; do
state=0 #reset state to okay
filename=$(basename -- $TARGET)
# Parse the Certifiate
expirationdate=$(date -d "$(: | openssl x509 -in $TARGET -text -noout | grep 'Not After' |awk '{print $4,$5,$7}')" '+%s');

inwarndays=$(($(date +%s) + (86400*$WARN_DAYS)));
incritdays=$(($(date +%s) + (86400*$CRIT_DAYS)));


if [ $leastexpirationdate -gt $expirationdate ] || [ $leastexpirationdate -eq 0 ]; then
leastexpirationdate=$expirationdate
leastexpirationcert=$filename
fi

expirydays=$(( ($expirationdate-$(date +%s)) /86400))
if [ $(date +%s) -gt $expirationdate ]; then
state=2 #Check_MK's Critical-State
desc="$desc $filename has already expired!"

elif [ $incritdays -gt $expirationdate ]; then
state=2 #Check_MK's Warning-State
desc="$desc $filename expires in $expirydays Days,"

elif [ $inwarndays -gt $expirationdate ]; then
state=1 #Check_MK's Warning-State
desc="$desc $filename expires in $expirydays Days,"

elif [ $inwarndays -lt $expirationdate ]; then
:

else #Set unknown if output is garbage
state=3 #Check_MK's  Unknown-State
exit 3
fi;
done

if [ $state -eq 0 ]; then
desc="All certs in folder $1 are valid, $leastexpirationcert will expire next in $expirydays days ($(date -d @$expirationdate '+%Y-%m-%d'))"
fi

# Finally Check_MK output
echo "$state SSL-Certs_$folder - $desc"
}

# define you folders here - currently .crt-files only to exclude private keys
#check_certs_in_folder "/some/path"
#check_certs_in_folder "/some/other/path"
